spring:
  application:
      name: "DiskSync"
  datasource:
      url: "${URL_DB}/${DATABASE}"
      username: ${USERNAME}
      password: ${PASSWORD}
      driver-class-name: "org.postgresql.Driver"
      datasource: ${DATABASE}
  jpa:
    hibernate:
        ddl-auto: "update"
server:
  port: ${PORT}

api:
  security:
    token:
      secret: ${JWT_SECRET}

  spotify:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: "http://localhost:8082/callback"